### ISSUE TITLE
SMTP errors for notification for new added entries

### ISSUE THREAD

**Issue by dniccum** [MaxLazar/mx-notify-control#6]
Hi I am trying to use MX Notify to send notifications to an entire member group when a new entry is added to an ExpressionEngine site that I am building. Currently I am using Mandrill as my SMTP email provider. Mandrill has served me well on many EE sites that I have built in the past because its easy and reliable. When a new entry is added the emails get sent but are not getting delivered due to an **invalid sender** error that I am getting from Mandrill.

After consulting their support team, they said that it is due to the fact that messages are missing the appropriate headers. Is this something that I can control from my message templates, or is there a bug within MX notify that needs to be fixed? Any feedback would be appreciated. Thanks.

**Comment by dniccum** [comment]
I was able to fix this. I changed the if code block starting at line 982 from:

```
		if (count($emailTo) != 0 )
		{
			foreach ($emailTo as $key => $val)
			{
				$this->EE->email->to($val['mbr_email']);
				$this->EE->email->subject($this->templater($email_sabj_tmp, $val));
				$this->EE->email->message(entities_to_ascii($this->templater($msg_body_tmp, $val)), (($plaintext_alt_tmp != '') ? $this->templater($plaintext_alt_tmp, $val) : ''));
				$this->EE->email->Send();
			}
		}
```

to

```
		if (count($emailTo) != 0 )
		{
			foreach ($emailTo as $key => $val)
			{
                $this->EE->email->initialize();
                $this->EE->email->from($site_settings['email_' . $iRow] != '' ? $site_settings['email_' . $iRow] :  $this->EE->config->item('webmaster_email'), ($site_settings['from_' . $iRow] != '') ? $site_settings['from_' . $iRow] : $this->EE->config->item('webmaster_name'));
                $this->EE->email->to($val['mbr_email']);
                $this->EE->email->subject($this->templater($email_sabj_tmp, $val));
                $this->EE->email->message(entities_to_ascii($this->templater($msg_body_tmp, $val)), (($plaintext_alt_tmp != '') ? $this->templater($plaintext_alt_tmp, $val) : ''));
                $this->EE->email->Send();
			}
		}
```

I will be submitting a patch.

**Comment by MaxLazar** [comment]
Thanks for patch!
